### PR TITLE
Correction bug MailTo

### PR DESCRIPTION
**Pull request by JcrGit**
Correction bug MailTo

### CODE REVIEW

**Comment by nricheton** [comment]
Can one of the admins verify this patch?

**Comment by fxbonnet** [comment]
Did you check that it does not break the build? 4.x branch pull request are not automatically built on the continuous integration.

**Comment by astik** [comment]
I just add the .Travis.yml file that was needed to trigger travis build.
A build occured and finished with failure. Apparently a dependency couldn't be resolved :
```
[ERROR] Failed to execute goal on project esigate-core: Could not resolve dependencies for project org.esigate:esigate-core:jar:4.4-SNAPSHOT: Failed to collect dependencies at spy:memcached:jar:2.5: Failed to read artifact descriptor for spy:memcached:jar:2.5: Could not transfer artifact spy:memcached:pom:2.5 from/to spy (http://bleu.west.spy.net/~dustin/m2repo/): Failed to transfer file: http://bleu.west.spy.net/~dustin/m2repo/spy/memcached/2.5/memcached-2.5.pom. Return code is: 410 , ReasonPhrase:Gone. -> [Help 1]
```
This is not a bug relative to this PR though.

**Comment by astik** [comment]
If someone find a solution for the missing dependency on 4.x branch, you may need to add the travis conf file to the PR in order to have it tested.

**Comment by fxbonnet** [comment]
This dependency does not exist anymore. In the trunk, we replaced it by:
``` xml
<dependency>
	<groupId>net.spy</groupId>
	<artifactId>spymemcached</artifactId>
	<version>2.10.3</version>
	<scope>compile</scope>
	<optional>true</optional>
</dependency>
```

**Comment by astik** [comment]
I won't be able to change this dependencies this week, I'll leave it to you =)

**Comment by nricheton** [comment]
Note : my previous message was posted by my jenkins instance. Replying "please test this" by a project admin will trigger a build. 

astik : please prevent travis to build external, unverified code.

**Comment by nricheton** [comment]
please test this

**Comment by nricheton** [comment]
test this please

**Pull request merged**
